### ISSUE TITLE
mem_fetch should push DS (not dict)

### ISSUE THREAD

**Issue by postspectacular** [phaendal/documentation-forth#2]
Just an issue in the 004, 005 & 006 C versions (JS is fine), e.g.

https://github.com/phaendal/documentation-forth/blob/master/006.interactive_rstack_recur/c-sample/main.c#L403

```
void w_mem_fetch () {
  DictValue d = dpop();
  pushDict(dict[d.number]); // ->> dpush
  next();
}
```

**Comment by phaendal** [comment]
ouch! Thank you!
